info_app/urls.py
from django.urls import path
from info_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'info_app'

urlpatterns = [
    path('about/',views.view_about.as_view(),name='about'),
    # path('testimonials/',views.view_testimonial.as_view(),name='testimonials'),
    path('contact/',views.view_contact,name='contact'),
    path('contact/thanks',views.view_thanks.as_view(),name='thanks'),
    path('portfolio/',views.view_joblist.as_view(),name='joblist'),
    path('portfolio/<int:pk>/',views.view_jobdetails.as_view(),name='jobdetails'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rhccommercial/urls.py
from django.contrib import admin
from django.urls import path,include
from info_app import views

urlpatterns = [
    # path('',views.IndexView.as_view(),name='index'),
    path('',views.view_joblist_index.as_view(),name='index'),
    # path('',views.view_testimonial_index.as_view(),name='testimonial_index'),
    path('admin/', admin.site.urls),
    path('',include('info_app.urls',namespace='info_app'))
]

info_app/models.py
from django.db import models

# Create your models here.
class model_testimonial(models.Model):
    person = models.CharField(max_length=128)
    company = models.CharField(max_length=128)
    quote = models.CharField(max_length=512,blank=True)
    personpic = models.ImageField()

    def __str__(self):
        return self.person

class model_job(models.Model):
    title = models.CharField(max_length=128)
    location = models.CharField(max_length=128)
    description = models.CharField(max_length=512)
    quote = models.CharField(max_length=512,blank=True)
    mainpic = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("info_app:jobdetails",kwargs={'pk':self.pk})

class model_jobpic(models.Model):
    pic = models.ImageField()
    job = models.ForeignKey(model_job,models.CASCADE,related_name='jobpic')

class model_jobnum(models.Model):
    number = models.CharField(max_length=128)

    def __str__(self):
        return self.number

info_app/forms.py
from django import forms

class form_contact(forms.Form):
    name  = forms.CharField(label='Your name', max_length=100)
    email  = forms.EmailField(label='Email', max_length=100)
    subject = forms.CharField(label='Subject', max_length=100)
    message = forms.CharField(label='Message', widget=forms.Textarea)

info_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from . import forms
from django.urls import reverse_lazy,reverse
from django.views.generic import (View,TemplateView,ListView,DetailView,FormView)
from django.core.mail import send_mail
from random import randint

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class view_joblist_index(ListView):
    context_object_name = 'job_list_index'
    model = models.model_job

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        max_id = models.model_testimonial.objects.all().order_by("-id")[0]
        # max_id = models.model_testimonial.objects.all().aggregate(max_id=max("id"))['max_id']
        while True:
            pk = randint(0, max_id.pk)
            testimonial = models.model_testimonial.objects.filter(pk=pk).first()
            if testimonial:
                context['testimonial'] = testimonial
                return context

    template_name = 'index.html'


class view_testimonial_index(ListView):
    context_object_name = 'testimonial_list_index'
    model = models.model_testimonial
    template_name = 'index.html'

class view_about(ListView):
    context_object_name = 'testimonial_list_about'
    model = models.model_testimonial
    template_name = 'info_app/about.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        jobnumber = models.model_jobnum.objects.filter(pk=1).first()
        context['jobnumber'] = jobnumber
        return context

class view_testimonial(ListView):
    context_object_name = 'testimonial_details'
    model = models.model_testimonial
    template_name = 'info_app/testimonials.html'

def view_contact(request):
    if request.method == 'POST':
        form = forms.form_contact(request.POST)
        if form.is_valid():
            # send email code goes here
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']
            sender_subject = form.cleaned_data['subject']

            message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
            send_mail(sender_subject, message, sender_email, ['michelconn@outlook.com'],fail_silently=False,)
            form = 'Thanks for contacting us!'
            return render(request, 'info_app/thanks.html', {'form': form})
    else:
        form = forms.form_contact()

    return render(request, 'info_app/contact.html', {'form': form})

class view_thanks(TemplateView):
    template_name = 'thanks.html'

class view_joblist(ListView):
    context_object_name = 'job_list'
    model = models.model_job
    template_name = 'info_app/job_list.html'

class view_jobdetails(DetailView):
    context_object_name = 'job_details'
    model = models.model_job
    template_name = 'info_app/job_detail.html'

info_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>
        {% block title_block %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'info_app/dependencies/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'info_app/dependencies/jquery-3.3.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'info_app/dependencies/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'info_app/dependencies/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'info_app/dependencies/hammer.js' %}"></script>
    <link rel="stylesheet" href="{% static 'info_app/dependencies/w3.css' %}">
    <link rel="stylesheet" href="{% static 'info_app/dependencies/css.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block style_block %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'info_app/css/base.css' %}">

</head>

<body>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<div class='logobar'>
  <a href="{% url 'index' %}"><img src="{% static 'info_app/images/RHCC.jpg' %}" alt=""></a>
</div>

<nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark main-nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#RHCCnavbar" aria-controls="RHCCnavbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse"  id="RHCCnavbar">
    <ul class="nav navbar-nav mx-auto">
      <li class="nav item active">
        <a class='nav-link' href="{% url 'info_app:about' %}">About Us</a>
      </li>
      <li class="nav item active">
        <a class='nav-link' href="{% url 'info_app:contact' %}">Contact</a>
      </li>
      <li class="nav item active">
        <a class='nav-link' href="{% url 'info_app:joblist' %}">Portfolio</a>
      </li>
    </ul>
  </div>
</nav>

  {% block body_block %}

  {% endblock %}

<div class="footer">
  <table align='center'>
    <td valign="top">
      <p><u>Who we are</u> <br>Leaders in quality commercial claims, consulting, and contracting</p>
    </td>
    <td valign="top">
      <p><u>Home Office</u><br><a href="http://maps.google.com/?q=1772 Pounds Rd Stone Mountain GA 30087" target="_blank">1772 Pounds Rd Stone Mountain GA 30087</a></p>
    </td>
    <td valign="top" style="word-wrap:break-word">
      <p><u>Contact</u><br><a href="mailto:michelconn@outlook.com">michelconn@outlook.com</a> <br><a href="tel:1-816-261-0353">Tel: 816-261-0353</a> <br>Fax: 816-261-0353</p>
    </td>
    <td valign="top">
      <p><u>Contact</u><br>
        <a target="_blank" href="https://www.facebook.com/michel.conn/"><img src="{% static 'info_app/images/Facebook_Logo_2023.png' %}" style="width:42px;height:42px;"></atarget="_blank">
        <a target="_blank" href="https://www.linkedin.com/in/michel-conn-80907755/"><img src="{% static 'info_app/images/In-Blue-40@2x.png' %}" style="width:42px;height:42px;"></atarget="_blank">
      </p>
    </td>
  </table>
</div>

</body>

</html>

info_app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - Home
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/index.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1 class="display-3 w3-animate-right">Our Mission</h1>
    <p class="lead w3-animate-left">
    We are Leaders in quality commercial claims, consulting, and contracting. At RHC Contracting, honesty is the cornerstone of our work ethics and we would welcome the opportunity to earn your trust.
    Hiring RHC Contracting as your professional consultant ensures that your claim is handled correctly and that you are being delivered the best service in the industry.
    You can be confident knowing we will take care of everything.
    {# If you still aren't sure, just ask our business associates about us. #}
    </p>
  </div>
</div>

<div class="container" id="rowcont">
  <div class="row">
    <div class="col-md-2 d-flex align-items-center">
      <a href="{% url 'info_app:about' %}">
      <img src="{{testimonial.personpic.url}}" alt="{% static 'info_app/images/person-light.png' %}" class="img-fluid" style="margin-bottom:10px;border:1px solid #7b3a20;">
    </a>
    </div>
    <div class="col-md-3 d-flex align-items-center justify-content-center">
      <blockquote class="blockquote">
        <a href="{% url 'info_app:about' %}">
        <p class="mb-0" style="color:white">"{{testimonial.quote}}"</p>
        <footer class="blockquote-footer">{{testimonial.person}} from <cite title="Source Title">{{testimonial.company}}</cite></footer>
        </a>
      </blockquote>
     </div>
    <div class="col-md-7">
      <h3>Portfolio</h3>
      <div class="w3-content w3-display-container" id="indexSlidShow">
        {% for jobindex in job_list_index %}
        <div class="w3-display-container mySlides" style="text-align:center;">
          <a href="{% url 'info_app:joblist' %}">
          <img src="{{jobindex.mainpic.url}}" class="w3-animate-opacity" >
          </a>
          <div class="w3-display-bottomleft w3-large w3-container w3-padding-16 w3-animate-opacity" style="background-color:rgba(0,0,0,0.7);color:white;">
            {{jobindex.title}}
          </div>
        </div>
        {% endfor %}
        <button class="w3-button w3-display-left btn" onclick="plusDivs(-1)" style="background-color:rgba(255,255,255,0.9)">&#10094;</button>
        <button class="w3-button w3-display-right btn" onclick="plusDivs(+1)" style="background-color:rgba(255,255,255,0.9)">&#10095;</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static '/info_app/js/index.js' %}"></script>

{% endblock %}

info_app/templates/info_app/about.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - About
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/about.css' %}">
{% endblock %}

{% block body_block %}

<div class="container" id="aboutContainer">
<<<<<<< HEAD
    <div class="jumbotron" id="aboutjum">
        <div class="row">
            <div class="col-md-9">
                <p style="font-size:1.3em;">
                    Our objective at RHC Contracting is to provide outstanding service.
                    Which is why we have a quality control person at every building insuring the completed claim meets our high standards.
                    Our policies have proven extremely effective in minimizing call backs and providing excellent service.
                    <br><br>
                    We are based on the belief that our customers' needs are of the utmost importance and we guarantee our entire team will be committed to meeting those needs.
                    As a result, a high percentage of our business is from repeat customers, referrals, and Insurance companies.
                    <br><br>
                    We would welcome the opportunity to earn your trust and deliver you the best service in the industry.
                </p>
            </div>
            <div class="col-md-3">
                <img src="{% static 'info_app/images/family.jpg' %}" alt="">
            </div>
        </div>
=======
  <div class="jumbotron" id="aboutjum">
  <div class="row">
    <div class="col-md-9">
      <p style="font-size:1.3em;">
        Our objective at RHC Contracting is to provide outstanding service.
        Which is why we have a quality control person at every building insuring the completed claim meets our high standards.
        Our policies have proven extremely effective in minimizing call backs and providing excellent service.
        <br><br>
        We are based on the belief that our customers' needs are of the utmost importance and we guarantee our entire team will be committed to meeting those needs.
        As a result, a high percentage of our business is from repeat customers, referrals, and Insurance companies.
        <br><br>
        We would welcome the opportunity to earn your trust and deliver you the best service in the industry.
      </p>
>>>>>>> 1591031b15d1759ee8c82f8ad880e55b79d87635
    </div>
</div>
<div class="ribbon-container mx-auto">
    <div class="ribbon">
        <div class="row ribbon-content" id="stats">
            <div class="col-md d-flex align-items-center flex-wrap">
                <p class="text-center w3-animate-zoom" style="font-size:3em;width:100%;">{{jobnumber.number}}</p>
                <p class="text-center" style="font-size:3em;line-height:0;width:100%;">&#9866;</p>
                <p class="text-center" style="width:100%;">Projects Completed</p>
            </div>
            <div class="col-md">
                <div class="w3-content w3-display-container">
                    {% for testimonial in testimonial_list_about %}
                    <div class="mySlides">
                        <img src="{{testimonial.personpic.url}}" alt="{% static 'info_app/images/person-light.png' %}" class="img-fluid w3-animate-opacity">
                        <div class="bottom-left w3-animate-opacity d-flex align-items-end">
                            <blockquote class="blockquote">
                                <p class="quote" style="font-size:0.7em;margin:0;">"{{testimonial.quote}}"</p>
                                <footer class="blockquote-footer" style="font-size:0.7em;;margin:0;color:white">{{testimonial.person}} from <cite title="Source Title">{{testimonial.company}}</cite></footer>
                            </blockquote>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md d-flex align-items-center flex-wrap">
                <p class="text-center w3-animate-zoom" style="font-size:3em;width:100%;">2008</p>
                <p class="text-center" style="font-size:3em;line-height:0;width:100%;">&#9866;</p>
                <p class="text-center" style="width:100%;">Year Established</p>
            </div>
        </div>
    </div>
<<<<<<< HEAD
=======
    <div class="col-md d-flex align-items-center flex-wrap">
      <p class="text-center w3-animate-zoom" style="font-size:3em;width:100%;">2008</p>
      <p class="text-center" style="font-size:3em;line-height:0;;width:100%;">&#9866;</p>
      <p class="text-center" style="width:100%;">Year Established</p>
    </div>
  </div>
</div>
>>>>>>> 1591031b15d1759ee8c82f8ad880e55b79d87635
</div>
<div class="container" id="aboutContainer">
    <div class="jumbotron" id='servicesjum'>
        <div class="row" id='services'>
            <div class="col-md">
                <img src="{% static 'info_app/images/Shingle-_large_hail,_bruised.jpg' %}" alt="">
                <h5>Preclaim Planning</h5>
                <p>
                    Before filing your claim we want to complete our <u>5 Point Inspection</u> of your property.
                    This will insure that filing is the best option for you.
                    With our <u>5 Point Inspection</u> report you can rest easy that your
                    claims process will run smoothly.
                </p>
            </div>
            <div class="col-md">
                <img src="{% static 'info_app/images/512px-FEMA_-_33786_-_FEMA_contractor_inspects_a_mobile_home_in_California.jpg' %}" alt="">
                <h5>5 Point Inspection</h5>
                <ol>
                    <li>Review you policies</li>
                    <li>Inspect your property</li>
                    <li>Investigate the cause for the claim</li>
                    <li>Reserach the building type</li>
                    <li>Offer solutions to repair or replace</li>
                </ol>
            </div>
            <div class="col-md">
                <img src="{% static 'info_app/images/insurance-claim.jpg' %}" alt="">
                <h5>Claims Consulting</h5>
                <p>
                    As your Consultant we will insure that your claim gets handled quickly and in a
                    professional manner.
                </p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static '/info_app/js/about.js' %}"></script>

</script>
{% endblock %}

info_app/templates/info_app/contact.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - Contact
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/contact.css' %}">

{% endblock %}

{% block body_block %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v18.0" nonce="rLRa9XfI"></script>
<div class="container">
    <div class="accordion" id="accordionExample">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <h1>Inquiries</h1>
                    </button>
                </h5>
            </div>

            <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="inquiries">
                        <p>
                            For any inquiries, questions or commendations, please call <br>
                            <a href="tel:816-261-0353" style="color:black;">816-261-0353</a>
                            or fill out the form below:
                        </p>
                        <form method="post">
                            {% csrf_token %}
                            <input style="width:100%;" type="text"
                                   name="{{ form.name.name }}"
                                   id="{{ form.name.id_for_label }}"
                                   {% if form.name.value != None %}value="{{ form.name.value|stringformat:'s' }}" {% endif %}
                                   maxlength="{{ form.name.field.max_length }}" placeholder="{{ form.name.label }}"
                                   {% if form.name.field.required %}required{% endif %} /> <br>
                            <input style="width:100%;" type="text"
                                   name="{{ form.email.name }}"
                                   id="{{ form.email.id_for_label }}"
                                   {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}" {% endif %}
                                   maxlength="{{ form.email.field.max_length }}" placeholder="{{ form.email.label }}"
                                   {% if form.email.field.required %}required{% endif %} /> <br>
                            <input style="width:100%;" type="text"
                                   name="{{ form.subject.name }}"
                                   id="{{ form.subject.id_for_label }}"
                                   {% if form.subject.value != None %}value="{{ form.subject.value|stringformat:'s' }}" {% endif %}
                                   maxlength="{{ form.subject.field.max_length }}" placeholder="{{ form.subject.label }}"
                                   {% if form.subject.field.required %}required{% endif %} /> <br>
                            <textarea style="width:100%;" rows="6" type="textarea"
                                      name="{{ form.message.name }}"
                                      id="{{ form.message.id_for_label }}" placeholder="{{ form.message.label }}"
                                      {% if form.message.value != None %}value="{{ form.message.value|stringformat:'s' }}" {% endif %}
                                      maxlength="{{ form.message.field.max_length }}"
                                      {% if form.message.field.required %}required{% endif %}></textarea> <br>
                            <input class="btn btn-warning" type="submit" value="Submit" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <h1>Home Office</h1>
                    </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="homeOffice">
                        <p>
                            <a href="http://maps.google.com/?q=1772 Pounds Rd Stone Mountain GA" target="_blank">1772 Pounds Rd Stone Mountain GA</a> <br><br>
                            <a href="mailto:michelconn@outlook.com">michelconn@outlook.com</a> <br>
                            <a href="tel:1-816-261-0353">Tel: 816-261-0353</a> <br>
                            Fax: 816-261-0353
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        <h1>Employment</h1>
                    </button>
                </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="employment">
                        <p>
                            To apply for a job with RHC Contracting, please send a cover letter together with your C.V. to
                            <a style="color:black;" href="mailto:michelconn@outlook.com">michelconn@outlook.com.</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingFour">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        <h1>Social</h1>
                    </button>
                </h5>
            </div>
            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="socialCol">
                        <div class="row text-center dflex">
                            <div class="col-lg">
                                <h5>Facebook</h5>
                                <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" data-width="" data-height="" data-small-header="false" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/facebook" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div>                            <div class="col-lg">
                                <h5>Linkedin</h5>
                                <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
                                <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="michel-conn-80907755" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/michel-conn-80907755?trk=profile-badge">Michel Conn</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static '/info_app/js/contact.js' %}"></script>

{% endblock %}

info_app/templates/info_app/job_detail.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - Portfolio
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/job_detail.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <p></p>
        <p style="font-size:1.5em">
            <strong>{{job_details.title}}</strong> |
            <a href="http://maps.google.com/?q=1200 {{job_details.location}}"
               target="_blank" style='color:black'>
                <em>{{job_details.location}}</em>
            </a>
        </p>
        <a class="lightbox" href="#jobpiclightrow">
            <div class="row justify-content-md-center">
                {% for jobmedia in job_details.jobpic.all %}
                <div class="col justify-content-md-center">
                    <img class="center-block img-responsive"
                         style="length:100%" src="{{ jobmedia.pic.url }}" alt="No Image">
                </div>
                {% endfor %}
            </div>
        </a>
        <div class="row">
            <div class="col-md-9 justify-content-md-center">
                <p>{{job_details.description}}</p>
            </div>
            <div class="col-md-3 justify-content-md-center">
                <div class="w3-panel w3-leftbar">
                    <span style="font-size:3em;line-height:0.6em;opacity:0.2;margin:0;">&#10077;</span>
                    <p style="margin-top:0;"><i class="w3-serif w3-medium">{{job_details.quote}}</i></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="lightbox-target" id="jobpiclightrow">
    {% for jobmedia2 in job_details.jobpic.all %}
    <img class="mySlides w3-animate-opacity" src="{{ jobmedia2.pic.url }}" alt="No Image">
    <button class="w3-button w3-display-left w3-white w3-border" onclick="plusDivs(-1)">&#10094;</button>
    <button class="w3-button w3-display-right w3-white w3-border" onclick="plusDivs(+1)">&#10095;</button>
    {% endfor %}
    <a class="lightbox-close" href="#"></a>
</div>

<script type="text/javascript" src="{% static '/info_app/js/job_detail.js' %}"></script>
{% endblock %}

info_app/templates/info_app/job_list.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - Portfolio
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/job_list.css' %}">
{% endblock %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1 class="display-3">Our Work</h1>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
</div>

<!-- Container for the image gallery -->
<div class="imageslide">

    <!-- Full-width images with number text -->
    <div id="listSlidID">
        {% for jobindex in job_list %}
        <div class="mySlides justify-content-md-center">
            <div class="numbertext">{{jobindex.pk}} / 3</div>
            <a href="{{jobindex.id}}">
                <img class='w3-animate-opacity' src="{{jobindex.mainpic.url}}">
            </a>
            <div class="w3-display-topleft w3-container w3-padding-16">
                {{jobindex.pk}} / 3
            </div>
        </div>
        {% endfor %}
    </div>


    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <!-- Image text -->
    <div class="caption-container">
        <p id="caption"></p>
    </div>

    <!-- Thumbnail images -->
    <div class="row justify-content-md-center">
        {% for jobindex in job_list %}
        <div class="col justify-content-md-center">
            <img class="demo cursor" src="{{jobindex.mainpic.url}}" style="width:100%" onclick="currentSlide({{jobindex.pk}})" alt="{{jobindex.title}}">
        </div>
        {% endfor %}
    </div>
</div>

<script type="text/javascript" src="{% static '/info_app/js/job_list.js' %}"></script>

{% endblock %}

info_app/templates/info_app/thanks.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
RHCC - Contact
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/contact.css' %}">
{% endblock %}

{% block body_block %}

<div class="jumbotron text-center">
  <h1 class="display-3">Thank you!</h1>
  <p class="lead">Your email was sent and we will get back to you as soon as we can.</p>
  <p>Return <a href="/" style="color:black;">home</a></p>
</div>

{% endblock %}